// Run against npm run dev with playwright-cli run-code --filename local/followup_ui_check.js.
async page => {
  const check=(value,message)=>{if(!value)throw new Error(message);};
  const origin=new URL(page.url()).origin, errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  const task={agent:'codex',dataset:'/example/measurements.csv',target:'label',objective:'Predict short or long from length and width',metric:'accuracy',minutes:5,trials:3,searchModels:false,model:'DecisionTreeClassifier',output:'py',exportModel:true,exportFormat:'native',validation:'holdout',folds:3,seeds:[42],testFraction:.2,holdoutFraction:.2,splitStrategy:'independent',groupColumn:'',timeColumn:'',assetColumns:[],policy:{augmentation:false,regularization:false,features:false,tuning:true,pretrained:false,ensemble:false}};
  const run={id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',task,status:'completed',phase:'complete',createdAt:'2026-01-01T00:00:00Z',startedAt:null,elapsed:125,logs:[],best:'trial-003',score:.96,testScore:.94,next:3,baseline:{name:'Most frequent class',score:.52,deviation:0},trials:[.83,.91,.96].map((score,index)=>({id:`trial-00${index+1}`,name:['Decision tree','Deeper tree','Pruned tree'][index],phase:'refinement',score,status:'accepted',duration:30,detail:'Measured on the same validation split.',artifact:`trial-00${index+1}/train.py`}))};
  let runs=[run],release=null,requestBody=null,fail=false;
  await page.route(origin+'/**',async route=>{
    const path=new URL(route.request().url()).pathname;
    const json=(value,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(value)});
    if(path==='/health')return json({mode:'hosted'});
    if(path==='/account/session')return json({username:'kavinravi',csrf:'test-session'});
    if(path==='/account/methods')return json([]);
    if(path==='/account/workspace')return json({ready:true});
    if(path==='/api/providers')return json([{id:'codex',name:'Codex',installed:true,authenticated:true,capability:{status:'verified'}}]);
    if(path==='/api/tools')return json([{id:'runtime',status:'Ready'}]);
    if(path==='/api/runs')return json(runs);
    if(path.endsWith('/artifacts'))return json([{path:'final/helix-solution.zip',size:100}]);
    if(path.endsWith('/messages')){
      requestBody=route.request().postDataJSON();
      await new Promise(resolve=>{release=resolve;});
      if(fail)return json({error:'Test connection failure'},400);
      (run.messages ||= []).push({id:String(run.messages?.length||0),message:requestBody.message,mode:requestBody.mode,status:'pending',createdAt:new Date().toISOString()});
      return json(run,202);
    }
    return route.continue();
  });
  await page.setViewportSize({width:1440,height:1000});
  await page.reload();
  await page.getByRole('navigation',{name:'Saved experiments'}).getByRole('button',{name:task.objective,exact:true}).click();
  if(await page.getByRole('button',{name:'Close dialog',exact:true}).isVisible()) await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  const composer=page.getByRole('textbox',{name:'Follow-up message'});
  await composer.waitFor();
  check((await page.locator('.composer-dock').boundingBox()).height<210,'Finished composer must stay compact');
  check(await page.getByRole('img',{name:/Validation accuracy/}).count()===1,'Validation chart is missing');
  check(await page.getByText('Final model · training loss',{exact:true}).count()===0,'Do not invent a loss curve for a tree');
  await page.getByRole('button',{name:'Download solution',exact:true}).waitFor();
  await page.screenshot({path:'/tmp/helix-followup-desktop.png'});
  await composer.fill('Why did pruning improve validation accuracy?');
  await page.getByRole('button',{name:'Send follow-up',exact:true}).click();
  await page.getByText('SENDING',{exact:true}).waitFor();
  check(await page.locator('.user-message').getByText('Why did pruning improve validation accuracy?',{exact:true}).count()===1,'Sent question must appear immediately');
  check(await composer.inputValue()==='','Composer should clear after sending');
  release();
  await page.getByText('Thinking…',{exact:true}).waitFor();
  run.messages[0].status='completed';run.messages[0].reply='Pruning reduced overfitting. Validation accuracy improved from 83% to 96% on the same split.';
  await page.getByText(run.messages[0].reply,{exact:true}).waitFor();
  await page.reload();
  await page.getByRole('navigation',{name:'Saved experiments'}).getByRole('button',{name:task.objective,exact:true}).click();
  if(await page.getByRole('button',{name:'Close dialog',exact:true}).isVisible())await page.getByRole('button',{name:'Close dialog',exact:true}).click();
  await page.getByText(run.messages[0].reply,{exact:true}).waitFor();
  fail=true;release=null;
  await composer.fill('Keep this question after a failure');
  await page.getByRole('button',{name:'Send follow-up',exact:true}).click();
  await page.getByText('SENDING',{exact:true}).waitFor();release();
  await page.getByText('Test connection failure',{exact:true}).waitFor();
  check(await composer.inputValue()==='Keep this question after a failure','Failed request must restore the draft');
  await page.getByRole('button',{name:'Dismiss error'}).click();fail=false;release=null;
  await page.getByRole('combobox',{name:'Follow-up action'}).selectOption('trials');
  await page.getByRole('spinbutton',{name:'Minutes',exact:true}).fill('');
  check(await page.getByRole('spinbutton',{name:'Minutes',exact:true}).inputValue()==='','Budget field should clear');
  await page.getByRole('spinbutton',{name:'Minutes',exact:true}).fill('5');
  await page.getByRole('spinbutton',{name:'Trials',exact:true}).fill('1');
  await composer.fill('Try a shallower tree');
  await page.getByRole('button',{name:'Send follow-up',exact:true}).click();
  await page.getByText('SENDING',{exact:true}).waitFor();
  check(requestBody.mode==='trials'&&requestBody.trials===1&&requestBody.minutes===5,'Send explicit additional-trial budget');
  release();await page.getByText('Preparing more trials…',{exact:true}).waitFor();
  const child={...structuredClone(run),id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',messages:[],followup:{parentId:run.id,message:'Try a shallower tree',protocolHash:'same'},testScore:null,trainingHistory:[{step:1,loss:.8,accuracy:.6},{step:2,loss:.4,accuracy:.8},{step:3,loss:.2,accuracy:.95}]};
  runs=[child,run];Object.assign(run.messages[1],{status:'completed',reply:'Started one additional trial. The original result is saved.',childRunId:child.id});
  await page.getByRole('button',{name:'View additional trials →',exact:true}).click();
  await page.getByText('Additional trials · validation only',{exact:true}).waitFor();
  await page.getByText('Final model · training loss',{exact:true}).waitFor();
  await page.getByText('Final model · training accuracy',{exact:true}).waitFor();
  check(await page.getByText('Test accuracy',{exact:true}).count()===0,'No test score on continued trials');
  await page.getByRole('button',{name:'← Original experiment',exact:true}).click();
  await page.getByText(run.messages[0].reply,{exact:true}).waitFor();
  await page.setViewportSize({width:390,height:844});
  await composer.waitFor();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile must not overflow horizontally');
  check((await page.locator('.composer-dock').boundingBox()).height<230,'Mobile composer must remain compact');
  await page.screenshot({path:'/tmp/helix-followup-mobile.png'});
  check(errors.length===0,errors.join('\n'));
  return 'Follow-up UI passed: optimistic send, persisted replies, error recovery, bounded trial request, linked results, measured charts, compact desktop/mobile composer.';
}
